name: Release build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run make -- --platform win32 --arch x64

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: out/make/**/*.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: out/make/**/*.exe
