name: Release build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set package.json version
        id: package_version
        uses: KageKirin/set-node-package-version@v0
        with:
          version: ${{ steps.get_version.outputs.version-without-v }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

      - run: npm ci

      - run: npm run make -- --platform win32 --arch x64

      - name: Commit new version
        run: |
          git config --global user.name "GitHub Automation"
          git config --global user.email "automation@noemail.com"
          git commit package.json -m "CI: update version from tag"
          git push https://${{ github.token }}@github.com/neilenns/Collins-FMS-3000-Display

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: out/make/**/*.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: out/make/**/*.exe
